name: Manual Trigger Repository_dispatch

on:
  repository_dispatch:
    types: [opened, deleted]

jobs:
  printInfo:
    runs-on: ubuntu-latest
    steps:
      - name: Print Info
        run: |
          echo "client_payload: ${{ toJson(github.event.client_payload) }}"
          echo "Info: ${{ toJson(github) }}"
